#!/bin/bash
# curl -sL http://git.io/uinit | bash

Config()
{
	export DEBIAN_FRONTEND=noninteractive
	printf '%-20s %s\n' APT_REPO_URL \
		"${APT_REPO_URL:=${1:-http://free.nchc.org.tw/ubuntu/}}";
	printf '%-20s %s\n' SudoNopass_User \
		${SudoNopass_User:=${SUDO_USER}}
	printf '%-20s %s\n' SudoNopass_Config \
		${SudoNopass_Config:=/etc/sudoers.d/50_${SUDO_USER}_sh}
	echo "================================"
}

Boostrap()
{
	# allow local edit
	if [[ ! -f "$0" ]]; then
		echo "Download uinit to PWD..."
		curl -sL http://git.io/uinit > uinit
		chmod u+x uinit
		echo "If you want change settings, press Ctrl-C now."
		echo "Sleep 5 seconds..."
		sleep 5
		exec sudo bash uinit "$@"
	fi

	if (( $(id -u) != 0 )); then
		exec sudo bash "$0" "$@"
	fi
}

Ubuntu_Repo_Config()
{
	if [ -e /etc/lsb-release ]; then
		source /etc/lsb-release
		cat <<-EOF > /etc/apt/sources.list
		deb $APT_REPO_URL $DISTRIB_CODENAME main restricted universe multiverse
		deb $APT_REPO_URL $DISTRIB_CODENAME-security main restricted universe multiverse
		deb $APT_REPO_URL $DISTRIB_CODENAME-updates main restricted universe multiverse
		deb $APT_REPO_URL $DISTRIB_CODENAME-backports main restricted universe multiverse
		deb-src $APT_REPO_URL $DISTRIB_CODENAME main restricted universe multiverse
		deb-src $APT_REPO_URL $DISTRIB_CODENAME-security main restricted universe multiverse
		deb-src $APT_REPO_URL $DISTRIB_CODENAME-updates main restricted universe multiverse
		deb-src $APT_REPO_URL $DISTRIB_CODENAME-backports main restricted universe multiverse
		EOF
	fi
}

Ubuntu_Repo_Timestamp()
{
	if [ -e /etc/lsb-release ]; then
		source /etc/lsb-release
		cat <<-EOF >> /etc/apt/sources.list
		# $(date --rfc-3339=seconds) Auto generated by jcppkkk/prepare-ubuntu-server
		EOF
	fi
}

SudoNopass()
{
	if ! grep -q "^#includedir.*/etc/sudoers.d" /etc/sudoers;then
		echo "#includedir /etc/sudoers.d" >> /etc/sudoers
	fi
	( 
		umask 226
		echo "$SudoNopass_User ALL=(ALL) NOPASSWD:ALL" > "$SudoNopass_Config"
	)
}

grep -q 'EDITOR=vim' ~/.bashrc || echo 'EDITOR=vim' >> ~/.bashrc

# Update source list to local mirror

Boostrap $@
Config $@
set -xe
SudoNopass
Ubuntu_Repo_Config
Ubuntu_Repo_Timestamp

apt-get -yq update
apt-get install -y unattended-upgrades ntp git etckeeper nfs-common sysstat

echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
dpkg-reconfigure -plow unattended-upgrades
sed -ri "s/\/\/(.*-updates.*)/\1/" /etc/apt/apt.conf.d/50unattended-upgrades
cat <<-EOF > /etc/apt/apt.conf.d/10periodic
	APT::Periodic::Update-Package-Lists "1";
	APT::Periodic::Download-Upgradeable-Packages "1";
	APT::Periodic::Unattended-Upgrade "1";
	APT::Periodic::AutocleanInterval "7";
	Unattended-Upgrade::Remove-Unused-Dependencies "true";
EOF

git config --global user.name || git config --global user.name "root"
git config --global user.email || git config --global user.email "root@$(hostname)"

if grep '#VCS="git"' /etc/etckeeper/etckeeper.conf; then
	yes | etckeeper uninit
	sed -i -e 's/^VCS="bzr"/#VCS="bzr"/g' -e 's/^#VCS="git"/VCS="git"/g' /etc/etckeeper/etckeeper.conf
	cd /etc
	etckeeper init
fi

apt-get autoremove
aptitude full-upgrade -y
